version: '3.8'

services:
  expense-frontend:
    build: .
    container_name: expense-management-fe
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_API_BASE_URL=http://localhost:8080/api/v1
      - NUXT_PUBLIC_AUTH_API_BASE_URL=http://localhost:8080/api/v1/auth
